# Utilise l'image officielle de Nginx comme base
FROM nginx:latest

# Copie les fichiers HTML dans le répertoire par défaut de Nginx
COPY . /usr/share/nginx/html

# Le conteneur écoutera sur le port 80 par défaut (géré par Nginx)
EXPOSE 80